### PR TITLE
Integrate React with Redux 

### PR DESCRIPTION
**Pull request by omarbabou**
**In this pull request, I added the following elements:**

  - Use Redux store to display books.
  - Add some UI elements to components and make them dispatch actions.

### CODE REVIEW

**Review by HAMMAS-SALEEM — COMMENTED** [review]
# Invalid Pull Request :red_circle: :traffic_light: :rotating_light:

## Hey @omarbabou :wave: 

**You have made a great effort on your project :blush: and I can see that but unfortunately I can not proceed with a code review of your pull request due to the following reasons :receipt:**
## 1.
### Your Missing LInters
linter-missing

- [x] You didn't add stylint linter in your project. Please add it :blush:
## 2. Your Application broken
error


- [x] Your application is showing some kind of errors in the console window while starting. Please fix these errors because they are breaking your application :fearful:
### Once you implement all the changes you should be ready to submit your project for a review :rocket: :rocket:

Cheers and Happy coding!👏👏👏

### Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @HAMMAS-SALEEM in your question so I can receive the notification. You can reach out to me on slack by searching my name (Hammas Bin Saleem) for any explanation.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by sja-thedude — CHANGES_REQUESTED** [review]
## Required Changes ♻️

Hi @omarbabou, This is @sja-thedude your code reviewer.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

768070f3-bc9a-4aba-b8bc-25793e00ea1e_text

## Highlights
✔️ Professional Readme
✔️ Correct gitflow
✔️ All linters passing

## Required 
- [x] Kindly make sure to fix the error which occurred when I tried running npm install.
Screenshot 2022-08-17 at 4 23 20 PM

- [x] Kindly make sure that add, and remove functions work correctly and also the check status button displays under construction upon clicking.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by omarbabou** [comment]
Hello @sja-thedude Hope you're doing well.

I'd like to inform you that am not using `npm` as package manager command but I use `Yarn` instead.

Please Run the following commands : `yarn install` to install` node_modules`, `yarn start ` to run the application instead of `npm start`. 
Thanks

**Review by prolajumokeoni — APPROVED** [review]
Hi @omarbabou, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
- No linter errors ✅ 
- Git flow was used correctly 🚀 
- Good Pr title and description 💪🏿 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by prolajumokeoni** [comment]
> Hello @sja-thedude Hope you're doing well.
> 
> I'd like to inform you that am not using `npm` as package manager command but I use `Yarn` instead.
> 
> Please Run the following commands : `yarn install` to install` node_modules`, `yarn start ` to run the application instead of `npm start`. Thanks

Everything works well 👍🏿

**Pull request merged**
